source 'http://rubygems.org'

gem 'rails'
gem 'sqlite3-ruby', :require => 'sqlite3'
#START_HIGHLIGHT
group :development, :test do
  gem "rspec-rails"
  gem "cucumber-rails", :require => false
  gem "webrat"
  gem "database_cleaner"
end
#END_HIGHLIGHT

